#!/usr/bin/env python3
"""Use VideoJudge to score independent LongQA answers against video evidence."""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
import hashlib
import json
import math
import os
import re
import time
from typing import Any

from longqa_utils import (
    apply_subset,
    build_prediction_row,
    normalize_answer,
    parse_mcq_options,
    sample_key,
)
from run_generate_longqa_grounded import extract_frames_by_indices, load_jsonl
from run_generate_longqa_proofpack import baseline_uniform_indices
from run_generate_longqa_uncertainty import _index_jsonl, _video_metadata


RATING_GUIDELINES = """You are provided with a video, a corresponding instruction, and a response generated by a model.

Rating Guidelines:
- Rating 5: Fully accurate, complete, and well-grounded. The response precisely follows the instruction with no notable errors or omissions.
- Rating 4: Mostly accurate with minor issues. The response preserves the key meaning and relevance, with only small lapses in detail or precision.
- Rating 3: Partially correct. The response conveys the general idea but includes noticeable errors, omissions, or misinterpretations.
- Rating 2: Poor alignment. The response has serious flaws and only loosely relates to the instruction or video.
- Rating 1: Unrelated or incorrect. The response fails to reflect the video or follow the instruction meaningfully.

Input:
Instruction:
{instruction}

Response:
{response}

Output (Strict Format):
<rubric>{{an instruction-specific 1-5 rubric grounded in the video}}</rubric>
<thinking>{{your reasoning and explanation for the rating}}</thinking>
<score>{{integer score from 1 to 5}}</score>"""


def resolve(path: str | None) -> str | None:
    if path is None or os.path.isabs(path):
        return path
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), path)


def answer(row: dict[str, Any]) -> str:
    return normalize_answer(row.get("mcq_answer_parsed") or row.get("mcq_answer"))


def valid_answer(value: str) -> bool:
    return value in {"A", "B", "C", "D"}


def majority_fallback(branch_answers: dict[str, str]) -> str:
    valid = [value for value in branch_answers.values() if valid_answer(value)]
    if not valid:
        raise RuntimeError("No valid independent candidate answer is available")
    counts = Counter(valid)
    maximum = max(counts.values())
    return next(value for value in valid if counts[value] == maximum)


def parse_score(raw: str) -> float | None:
    tagged = re.findall(
        r"<score>\s*([1-5](?:\.\d+)?)\s*</score>", raw, flags=re.IGNORECASE
    )
    candidates = tagged or re.findall(
        r"\b(?:rating|score)\s*[:=]\s*([1-5](?:\.\d+)?)\b",
        raw,
        flags=re.IGNORECASE,
    )
    if not candidates:
        return None
    value = float(candidates[-1])
    return value if 1.0 <= value <= 5.0 else None


def evenly_spaced(values: list[int], count: int) -> list[int]:
    if count <= 0 or not values:
        return []
    if len(values) <= count:
        return values
    if count == 1:
        return [values[len(values) // 2]]
    return [values[round(index * (len(values) - 1) / (count - 1))] for index in range(count)]


def selected_indices(record: dict[str, Any]) -> list[int]:
    if isinstance(record.get("selected"), list):
        return [int(item["frame_index"]) for item in record["selected"]]
    if isinstance(record.get("final_indices"), list):
        return [int(value) for value in record["final_indices"]]
    return []


def build_evidence_indices(
    primary: dict[str, Any],
    pivot: dict[str, Any],
    option: dict[str, Any],
    uncertainty: dict[str, Any],
    total_frames: int,
    max_frames: int,
    evidence_mode: str,
) -> tuple[list[int], dict[str, int]]:
    primary_indices = [int(value) for value in primary.get("multicandidate_judge_frames", [])]
    if not primary_indices:
        primary_indices = baseline_uniform_indices(total_frames, min(64, max_frames))
    primary_indices = sorted({value for value in primary_indices if 0 <= value < total_frames})
    if evidence_mode == "primary":
        chosen = evenly_spaced(primary_indices, max_frames)
        return chosen, {"primary": len(chosen)}

    pools = {
        "primary": primary_indices,
        "pivot": selected_indices(pivot),
        "option_quota": selected_indices(option),
        "uncertainty": selected_indices(uncertainty),
        "uniform": baseline_uniform_indices(total_frames, 64),
        "endpoint": [
            round(index * (total_frames - 1) / 63) for index in range(64)
        ] if total_frames > 1 else [0],
    }
    membership: dict[int, set[str]] = defaultdict(set)
    for source, values in pools.items():
        for value in values:
            value = int(value)
            if 0 <= value < total_frames:
                membership[value].add(source)

    # Keep the proven 64-frame primary pack intact, then use the remaining
    # budget for temporally distributed frames found by the other selectors.
    chosen_set = set(primary_indices[:max_frames])
    remaining = sorted(set(membership) - chosen_set)
    chosen_set.update(evenly_spaced(remaining, max_frames - len(chosen_set)))
    chosen = sorted(chosen_set)
    contributions = Counter()
    for frame_index in chosen:
        sources = membership.get(frame_index, {"primary"})
        for source in sources:
            contributions[source] += 1
    return chosen, dict(contributions)


def judge_instruction(row: dict[str, Any]) -> str:
    return (
        "Answer the following multiple-choice question using the chronological "
        "video evidence. The video may contain sampled evidence frames with gaps "
        "between them.\n\n"
        f"Question: {row['question']}\n\n"
        f"Answer choices:\n{row['mcq_options']}"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", default="../egolongqa/wearable_ai_2026_egolongqa_val_700.jsonl")
    parser.add_argument("--video-folder", default="../egolongqa/val")
    parser.add_argument("--subset-file", default=None)
    parser.add_argument("--candidate-predictions", action="append", required=True)
    parser.add_argument("--candidate-labels", nargs="+", required=True)
    parser.add_argument("--primary-predictions", required=True)
    parser.add_argument("--pivot-proofpack", required=True)
    parser.add_argument("--option-proofpack", required=True)
    parser.add_argument("--uncertainty-selection", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--eval-output", default=None)
    parser.add_argument(
        "--llm-model",
        default="VideoJudge/Qwen2.5-VL-7B-Instruct-VideoJudgeWithRubric-RS-20K",
    )
    parser.add_argument("--backend", choices=("vllm",), default="vllm")
    parser.add_argument("--tp", type=int, default=1)
    parser.add_argument("--concurrency", type=int, default=1)
    parser.add_argument("--max-frames", type=int, choices=(64, 120), default=64)
    parser.add_argument("--evidence-mode", choices=("primary", "union"), default="primary")
    parser.add_argument("--candidate-mode", choices=("unique", "all_options"), default="unique")
    parser.add_argument("--max-new-tokens", type=int, default=1024)
    parser.add_argument("--judge-all", action="store_true")
    parser.add_argument("--no-resume", action="store_true")
    parser.add_argument("--no-eval", action="store_true")
    args = parser.parse_args()
    if len(args.candidate_predictions) != len(args.candidate_labels):
        parser.error("candidate prediction and label counts must match")
    if args.evidence_mode == "primary" and args.max_frames != 64:
        parser.error("primary evidence mode requires --max-frames 64")
    return args


def fingerprint(args: argparse.Namespace) -> str:
    payload = {
        "candidates": [os.path.abspath(path) for path in args.candidate_predictions],
        "labels": args.candidate_labels,
        "primary": os.path.abspath(args.primary_predictions),
        "pivot": os.path.abspath(args.pivot_proofpack),
        "option": os.path.abspath(args.option_proofpack),
        "uncertainty": os.path.abspath(args.uncertainty_selection),
        "model": args.llm_model,
        "frames": args.max_frames,
        "evidence_mode": args.evidence_mode,
        "candidate_mode": args.candidate_mode,
        "max_new_tokens": args.max_new_tokens,
        "judge_all": args.judge_all,
        "subset": os.path.abspath(args.subset_file) if args.subset_file else None,
    }
    return hashlib.sha1(json.dumps(payload, sort_keys=True).encode()).hexdigest()[:16]


def main() -> None:
    from model import create_model, reset_prompt_token_stats, summarize_prompt_token_stats
    from run_generate_longqa_grounded import _run_eval

    args = parse_args()
    input_path = str(resolve(args.input))
    video_folder = str(resolve(args.video_folder))
    output_path = str(resolve(args.output))
    rows = apply_subset(load_jsonl(input_path), args.subset_file)
    candidates = {
        label: _index_jsonl(str(resolve(path)))
        for label, path in zip(args.candidate_labels, args.candidate_predictions)
    }
    primary = _index_jsonl(str(resolve(args.primary_predictions)))
    pivot = _index_jsonl(str(resolve(args.pivot_proofpack)))
    option = _index_jsonl(str(resolve(args.option_proofpack)))
    uncertainty = _index_jsonl(str(resolve(args.uncertainty_selection)))
    required = {sample_key(row) for row in rows}
    for label, indexed in {
        **candidates,
        "primary": primary,
        "pivot": pivot,
        "option": option,
        "uncertainty": uncertainty,
    }.items():
        missing = required - set(indexed)
        if missing:
            raise RuntimeError(f"{label} is missing {len(missing)} required rows")

    run_fingerprint = fingerprint(args)
    existing = [] if args.no_resume or not os.path.exists(output_path) else load_jsonl(output_path)
    start = 0
    for index, record in enumerate(existing[:len(rows)]):
        if sample_key(record) != sample_key(rows[index]) or record.get("videojudge_fingerprint") != run_fingerprint:
            break
        start += 1
    if len(existing) != start:
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with open(output_path, "w") as handle:
            for record in existing[:start]:
                handle.write(json.dumps(record) + "\n")
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    calls_expected = 0
    for row in rows:
        key = sample_key(row)
        branch_values = {
            label: answer(indexed[key]) for label, indexed in candidates.items()
        }
        primary_value = answer(primary[key])
        if not valid_answer(primary_value):
            primary_value = majority_fallback(branch_values)
        letters = {value for value in branch_values.values() if valid_answer(value)}
        letters.add(primary_value)
        if args.judge_all or len(letters) > 1:
            calls_expected += 4 if args.candidate_mode == "all_options" else len(letters)
    print(
        f"VideoJudge: rows={len(rows)} resume={start} expected_calls={calls_expected} "
        f"frames={args.max_frames} evidence={args.evidence_mode} candidates={args.candidate_mode} "
        f"fingerprint={run_fingerprint}"
    )

    model = create_model(
        "qwen", args.llm_model, backend=args.backend, tp_size=args.tp,
        concurrency=args.concurrency, max_frames=args.max_frames,
    )
    reset_prompt_token_stats()
    calls = 0
    begun = time.time()
    with model, open(output_path, "a" if start else "w") as handle:
        for index, row in enumerate(rows[start:], start=start):
            row_begun = time.perf_counter()
            key = sample_key(row)
            options = parse_mcq_options(row["mcq_options"])
            branch_answers = {label: answer(indexed[key]) for label, indexed in candidates.items()}
            primary_answer = answer(primary[key])
            if not valid_answer(primary_answer):
                primary_answer = majority_fallback(branch_answers)
            branch_answers["primary_27b"] = primary_answer
            proposed = set(branch_answers.values())
            should_judge = args.judge_all or len(proposed) > 1
            score_rows: dict[str, dict[str, Any]] = {}
            selected = primary_answer
            indices: list[int] = []
            contributions: dict[str, int] = {}
            if should_judge:
                video_path = os.path.join(video_folder, str(row["video_path"]))
                fps, total_frames = _video_metadata(video_path)
                if total_frames <= 0:
                    raise RuntimeError(f"Could not read video metadata: {video_path}")
                indices, contributions = build_evidence_indices(
                    primary[key], pivot[key], option[key], uncertainty[key],
                    total_frames, args.max_frames, args.evidence_mode,
                )
                frames = extract_frames_by_indices(video_path, indices)
                if len(frames) != len(indices):
                    raise RuntimeError(
                        f"Extracted {len(frames)}/{len(indices)} frames for {video_path}"
                    )
                letters = list(options) if args.candidate_mode == "all_options" else [
                    letter for letter in options if letter in proposed
                ]
                instruction = judge_instruction(row)
                for letter in letters:
                    response = options[letter]
                    messages = [{
                        "role": "user",
                        "content": RATING_GUIDELINES.format(
                            instruction=instruction, response=response,
                        ),
                    }]
                    candidate_begun = time.perf_counter()
                    error = None
                    raw = ""
                    score = None
                    try:
                        raw = str(model.generate_video_frames(
                            frames, messages, max_new_tokens=args.max_new_tokens
                        ))
                        score = parse_score(raw)
                        if score is None:
                            error = "missing valid <score> tag"
                    except Exception as exception:
                        error = f"{type(exception).__name__}: {exception}"
                    score_rows[letter] = {
                        "answer_text": response,
                        "score": score,
                        "raw": raw,
                        "error": error,
                        "seconds": round(time.perf_counter() - candidate_begun, 3),
                    }
                    calls += 1
                valid = {
                    letter: record["score"] for letter, record in score_rows.items()
                    if record["score"] is not None
                }
                if valid:
                    maximum = max(valid.values())
                    tied = [letter for letter, value in valid.items() if math.isclose(value, maximum)]
                    selected = primary_answer if primary_answer in tied else tied[0]

            prediction = build_prediction_row(row, selected, prompt_variant="videojudge_pointwise")
            prediction.update({
                "videojudge_applied": should_judge,
                "videojudge_model": args.llm_model,
                "videojudge_candidate_mode": args.candidate_mode,
                "videojudge_evidence_mode": args.evidence_mode,
                "videojudge_primary_answer": primary_answer,
                "videojudge_candidate_answers": branch_answers,
                "videojudge_scores": score_rows,
                "videojudge_selected": selected,
                "videojudge_fallback": selected == primary_answer,
                "videojudge_frames": indices,
                "videojudge_frame_timestamps": [round(value / max(fps, 1e-6), 3) for value in indices] if indices else [],
                "videojudge_frame_sources": contributions,
                "videojudge_seconds": round(time.perf_counter() - row_begun, 3),
                "videojudge_fingerprint": run_fingerprint,
            })
            handle.write(json.dumps(prediction) + "\n")
            handle.flush()
            print(f"  VideoJudge progress: {index + 1}/{len(rows)} calls={calls}/{calls_expected}")

    print(f"VideoJudge calls this invocation: {calls}")
    print(f"Runtime seconds: {time.time() - begun:.0f}")
    print(f"Context summary: {json.dumps(summarize_prompt_token_stats(), sort_keys=True)}")
    if not args.no_eval:
        _run_eval(input_path, output_path, resolve(args.eval_output))


if __name__ == "__main__":
    main()
